### ISSUE TITLE
firefoxHeadless in GebConfig does not work

### ISSUE THREAD

**Issue by GuopingJia** [brianjbayer/sample-login-geb-spock#6]
Below setup for firefoxHeadless in GebConfig does not work:

    firefoxHeadless {
        driver = {
            FirefoxOptions o = new FirefoxOptions()
            o.addArguments('--headless')
            new FirefoxDriver(o)
        }

All the tests failed with WebDriverException/DriverCreationException:

    geb.driver.DriverCreationException at NCSLoginPageSpec.groovy:37
        Caused by: org.openqa.selenium.WebDriverException at NCSLoginPageSpec.groovy:37
    geb.driver.DriverCreationException
        Caused by: org.openqa.selenium.WebDriverException
    geb.driver.DriverCreationException
        Caused by: org.openqa.selenium.WebDriverException

**Comment by GuopingJia** [comment]
Test with firefox works well. 

I don't see which gecko driver version you are using ?

I am using geckoDriverVersion = '0.20.1', together with gebVersion = '2.0' & seleniumVersion = '3.8.1'. 

My firefox client is running 61.0.1 (64 bits).

**Comment by brianjbayer** [comment]
Sorry, that I have not gotten to this sooner - life in the way and all that.  So, this all seems to work for me on my Mac including firefoxHeadless.  I did upgrade both Geckodriver to 0.21.0 and Firefox to 62.0 (64-bit) and it still works.  My geckodriver is installed via homebrew.  My Selenium and Geb versions are as listed in the pom file. 

Not sure that this helps, but please let me know if there is more info that I can supply. 

I did find this: http://www.automationtestinghub.com/selenium-headless-chrome-firefox/ using the setHeadless method.  Not sure if that will help.

**Comment by GuopingJia** [comment]
Thank you for spending time trying this out in your env. 

I've retried everything, including the setHeadless(). Unfortunately, it still had the same issue. All tests failed with DriverCreationException/WebDriverException. 

Here I post the detailed failure stacktrace. As mentioned, all tests work well with firefox. They are having the same GebConfig, excepting the setup for 'headless' option.

Below "org.openqa.selenium.WebDriverException: connection refused" really worried me. Not sure why there is no any issue in firefox ?

geb.driver.DriverCreationException: failed to create driver from callback 'script1536756625577751647493$_run_closure1$_closure6$_closure12@28f2192e'
        at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
        at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
        at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
        at geb.Configuration.createDriver(Configuration.groovy:382)
        at geb.Configuration.getDriver(Configuration.groovy:371)
        at geb.Browser.getDriver(Browser.groovy:111)
        at geb.report.PageSourceReporter.getPageSource(PageSourceReporter.groovy:42)
        at geb.report.PageSourceReporter.writePageSource(PageSourceReporter.groovy:38)
        at geb.report.PageSourceReporter.writeReport(PageSourceReporter.groovy:29)
        at geb.report.CompositeReporter.writeReport(CompositeReporter.groovy:31)
        at geb.Browser.report(Browser.groovy:931)
        at geb.spock.GebReportingSpec.report(GebReportingSpec.groovy:59)
        at geb.spock.GebReportingSpec.cleanup(GebReportingSpec.groovy:46)
Caused by: org.openqa.selenium.WebDriverException: connection refused
Command duration or timeout: 60.27 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'guoping-HP-Z640-Workstation', ip: '10.38.145.28', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-53-generic', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.Gecko013ProtocolResponse.lambda$new$0(Gecko013ProtocolResponse.java:39)
        at org.openqa.selenium.remote.Gecko013ProtocolResponse.lambda$getResponseFunction$2(Gecko013ProtocolResponse.java:90)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:142)
        at org.openqa.selenium.firefox.FirefoxDriver.&lt;init&gt;(FirefoxDriver.java:120)
        at script1536756625577751647493$_run_closure1.closure6$_closure12(script1536756625577751647493.groovy:83)
        at script1536756625577751647493$_run_closure1.closure6$_closure12(script1536756625577751647493.groovy)
        at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
        ... 14 more

**Comment by brianjbayer** [comment]
I'm sure that this is frustrating for you.  I'm not really seeing anything jumping out from that stack trace.  Some things that I might look at would be...
Ensuring that there is only one Firefox installed
Ensuring that there is only one geckodriver installed and it is appropriate 32 or 64 bit version
Running ./<path-to-firefox>/firefox -headless and examining the output

My other thoughts would be around the ports used by geckodriver and firefox and whether there are any conflicts.  

There's also this on Firefox and Geckodriver: http://www.automationtestinghub.com/selenium-3-0-launch-firefox-with-geckodriver/ which may help in manually triaging this setup.

Finally, and I'm thinking of also adding this to this project, try using a driver manager like https://github.com/bonigarcia/webdrivermanager

**Comment by GuopingJia** [comment]
Yes, there were lots of defunct firefox jobs on my system. Simple 'firefox -headless' could not start, complaining firefox already running. 

Restarting my Linux box seems to have fixed everything. Now it works with firefox headless mode. 

Thank you for your help. I am closing this ticket.

**Comment by brianjbayer** [comment]
Glad to hear that it is working. Reboot FTW.
